import React, {useEffect, useRef} from 'react';
import Head from 'next/head'
import Layout from "@/components/Layout";
import AnimeHeading from "@/components/AnimeHeading";
import profilePic from "../../public/images/profile/developer-pic-5.png"
import Image from "next/image";
import {useInView, useMotionValue, useSpring} from "framer-motion";
import Skills from "@/components/Skills";
import Education from "@/components/Education";
import {motion} from "framer-motion";
import TransitionPage from "@/components/TransitionPage";

const AnimatedNumbers = ({value, className="", isHovered}) => {
    const spanRef = useRef(" ");

    const motionValue = useMotionValue(0)
    const spring = useSpring(motionValue, {duration: 5000})
    const inView = useInView(spanRef)

    useEffect(()=>{
        if (inView) motionValue.set(value);
    },[motionValue, value, inView])

    useEffect(()=>{
        spring.on("change", (latest) => {
            if (spanRef.current && latest.toFixed(0) <= value)
                spanRef.current.textContent = `${latest.toFixed(0)}+`
        })
    },[spring, value]);

    return <span ref={spanRef} className={`${className} text-dark dark:text-light`} onMouseOver={() => isHovered("hovered")} onMouseLeave={() => isHovered("default")}></span>
};
const About = ({isHovered}) => {
    return (
        <>
            <Head>
                <title>Abubakar Siddique | About Page</title>
                <meta name="description" content="Generated by create next app"/>
            </Head>
            <main>
                <TransitionPage/>
                <Layout>
                    <div className="flex justify-center items-center text-center">
                        <AnimeHeading isHovered={isHovered} text={"Passion Fuels Purpose!"}/>
                    </div>
                    <div className="flex flex-col lg:flex-row justify-between items-center pt-7 pb-7 gap-8">
                        <div className="flex flex-col md:flex-row gap-8 justify-between items-center">
                            <div>
                                <h2 className="uppercase text-dark dark:text-light font-bold text-lg" onMouseOver={() => isHovered("hovered")} onMouseLeave={() => isHovered("default")}>
                                    Biography
                                </h2>
                                <p className="pt-3 font-medium text-dark dark:text-light" onMouseOver={() => isHovered("hovered")} onMouseLeave={() => isHovered("default")}>
                                    Hi, I&apos;m M.Abubakar Siddique, a full stack web developer with a passion for creating beautiful, functional,
                                    and user-centered digital experiences. With 2 years of professional experience in the field. I am always looking for
                                    new and innovative ways to bring my clients&apos; visions to life.
                                </p>
                                <p className="pt-3 font-medium text-dark dark:text-light" onMouseOver={() => isHovered("hovered")} onMouseLeave={() => isHovered("default")}>
                                    I believe that design is about more than just making things look pretty – it&apos;s about solving problems and
                                    creating intuitive, enjoyable experiences for users.
                                </p>

                                <p className="pt-3 font-medium text-dark dark:text-light" onMouseOver={() => isHovered("hovered")} onMouseLeave={() => isHovered("default")}>
                                    Whether I&apos;m working on a website, mobile app, or
                                    other digital product, I bring my commitment to design excellence and user-centered thinking to
                                    every project I work on. I look forward to the opportunity to bring my skills and passion to your next project.
                                </p>
                            </div>
                            <div className="order-first md:order-none bg-dark dark:bg-light rounded-3xl translate-x-3 translate-y-3">
                                <motion.div className="border-2 border-solid border-dark dark:border-light rounded-3xl p-5 bg-light dark:bg-dark -translate-x-3 -translate-y-3"
                                            initial={{transform: "translate(0rem, 0rem)"}}
                                            whileInView={{transform: "translate(-0.75rem, -0.75rem)", transition: {duration: 3} }}
                                            >
                                    <Image src={profilePic} alt="Abubakar" priority className="rounded-3xl bg-light dark:bg-dark" />
                                </motion.div>
                            </div>
                        </div>


                        <div className="flex flex-wrap lg:w-full items-center justify-center text-center gap-7">
                            <div>
                                <AnimatedNumbers isHovered={isHovered} value={10} className="font-bold text-2xl md:text-3xl"/>
                                <h2 onMouseOver={() => isHovered("hovered")} onMouseLeave={() => isHovered("default")} className="text-dark dark:text-light">Projects Completed</h2>
                            </div>
                            <div>
                                <AnimatedNumbers isHovered={isHovered} value={2} className="font-bold text-2xl md:text-3xl"/>
                                <h2 onMouseOver={() => isHovered("hovered")} onMouseLeave={() => isHovered("default")} className="text-dark dark:text-light">Years Of Experience</h2>
                            </div>
                        </div>
                    </div>
                </Layout>
                <Skills isHovered={isHovered}/>
                <Education isHovered={isHovered}/>
            </main>
        </>
    );
};

export default About;